# Makefile for libagchess and some sample code utilizing libagchess
# Yes - I know, it's a terrible makefile, but I'm really using this as an
# iPhone library, which means all the work I do is in Xcode, which doesn't
# generate makefiles.

Demo.exe : 
			g++ *.cpp libagchess/*.cpp -w -o Demo.exe
			
clean :
	rm *.o